services:
  basilasay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basilasay
    env_file:
      - .env
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true
