services:
  basilasay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basilasay
    environment:
      - PORT=${PORT:-3000}
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true
